@parking_app_HostAddress = http://localhost:5072

GET {{parking_app_HostAddress}}/weatherforecast/
Accept: application/json

### register
POST {{parking_app_HostAddress}}/api/parking/register
Content-Type: application/json

{
  "name": "def",
  "accountBalance": 0,
  "cars": [
    {
      "licensePlate": "DEF123",
      "userId": 2
    }
  ]
}

### begin parking
POST {{parking_app_HostAddress}}/api/parking/begin/1
Content-Type: application/json

# 1

### current parking
GET {{parking_app_HostAddress}}/api/parking/current/1
Content-Type: application/json

### end parking
POST {{parking_app_HostAddress}}/api/parking/end/3
Content-Type: application/json

# 2



### user details
GET {{parking_app_HostAddress}}/api/parking/details/1
Content-Type: application/json

### user detailscost
GET {{parking_app_HostAddress}}/api/parking/cost/1
Content-Type: application/json
